-- Reference data: the sector hierarchy shown in the "Sectors" select box.
-- Ids are the original <option value> attributes, i.e. stable business identifiers, so they are not generated.
CREATE TABLE sector (
    id         BIGINT       NOT NULL,
    name       VARCHAR(255) NOT NULL,
    parent_id  BIGINT,
    sort_order INTEGER      NOT NULL,
    CONSTRAINT pk_sector PRIMARY KEY (id),
    CONSTRAINT fk_sector_parent FOREIGN KEY (parent_id) REFERENCES sector (id),
    CONSTRAINT uq_sector_sort_order UNIQUE (sort_order),
    CONSTRAINT uq_sector_parent_name UNIQUE (parent_id, name)
);

CREATE INDEX idx_sector_parent_id ON sector (parent_id);

-- One saved form: the person's name, whether they agreed to the terms, and (via submission_sector)
-- the sectors they picked. Ownership is not stored: it lives in the HTTP session that created the row.
CREATE TABLE submission (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(255)             NOT NULL,
    agreed_to_terms BOOLEAN                  NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_submission PRIMARY KEY (id),
    CONSTRAINT ck_submission_name_not_blank CHECK (LENGTH(TRIM(name)) > 0),
    CONSTRAINT ck_submission_agreed_to_terms CHECK (agreed_to_terms = TRUE)
);

CREATE TABLE submission_sector (
    submission_id BIGINT NOT NULL,
    sector_id     BIGINT NOT NULL,
    CONSTRAINT pk_submission_sector PRIMARY KEY (submission_id, sector_id),
    CONSTRAINT fk_submission_sector_submission FOREIGN KEY (submission_id) REFERENCES submission (id) ON DELETE CASCADE,
    CONSTRAINT fk_submission_sector_sector FOREIGN KEY (sector_id) REFERENCES sector (id)
);

CREATE INDEX idx_submission_sector_sector_id ON submission_sector (sector_id);
