--
-- PostgreSQL database dump
--

\restrict vbhCLHJG6ozDEzrMDvCabfbYNmbRyS5fVcAqZsT5fcv1NsMsK6GYO9cRsnI8ivJ

-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


--
-- Name: sector; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sector (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    parent_id bigint,
    sort_order integer NOT NULL
);


--
-- Name: submission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.submission (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    agreed_to_terms boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_submission_agreed_to_terms CHECK ((agreed_to_terms = true)),
    CONSTRAINT ck_submission_name_not_blank CHECK ((length(TRIM(BOTH FROM name)) > 0))
);


--
-- Name: submission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.submission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.submission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: submission_sector; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.submission_sector (
    submission_id bigint NOT NULL,
    sector_id bigint NOT NULL
);


--
-- Data for Name: flyway_schema_history; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.flyway_schema_history VALUES (1, '1', 'create schema', 'SQL', 'V1__create_schema.sql', 817812148, 'sectors', '2026-09-16 17:40:56.70473', 20, true);
INSERT INTO public.flyway_schema_history VALUES (2, '2', 'seed sectors', 'SQL', 'V2__seed_sectors.sql', 658504705, 'sectors', '2026-09-16 17:40:56.748505', 6, true);


--
-- Data for Name: sector; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.sector VALUES (1, 'Manufacturing', NULL, 1);
INSERT INTO public.sector VALUES (19, 'Construction materials', 1, 2);
INSERT INTO public.sector VALUES (18, 'Electronics and Optics', 1, 3);
INSERT INTO public.sector VALUES (6, 'Food and Beverage', 1, 4);
INSERT INTO public.sector VALUES (342, 'Bakery & confectionery products', 6, 5);
INSERT INTO public.sector VALUES (43, 'Beverages', 6, 6);
INSERT INTO public.sector VALUES (42, 'Fish & fish products', 6, 7);
INSERT INTO public.sector VALUES (40, 'Meat & meat products', 6, 8);
INSERT INTO public.sector VALUES (39, 'Milk & dairy products', 6, 9);
INSERT INTO public.sector VALUES (437, 'Other', 6, 10);
INSERT INTO public.sector VALUES (378, 'Sweets & snack food', 6, 11);
INSERT INTO public.sector VALUES (13, 'Furniture', 1, 12);
INSERT INTO public.sector VALUES (389, 'Bathroom/sauna', 13, 13);
INSERT INTO public.sector VALUES (385, 'Bedroom', 13, 14);
INSERT INTO public.sector VALUES (390, 'Children’s room', 13, 15);
INSERT INTO public.sector VALUES (98, 'Kitchen', 13, 16);
INSERT INTO public.sector VALUES (101, 'Living room', 13, 17);
INSERT INTO public.sector VALUES (392, 'Office', 13, 18);
INSERT INTO public.sector VALUES (394, 'Other (Furniture)', 13, 19);
INSERT INTO public.sector VALUES (341, 'Outdoor', 13, 20);
INSERT INTO public.sector VALUES (99, 'Project furniture', 13, 21);
INSERT INTO public.sector VALUES (12, 'Machinery', 1, 22);
INSERT INTO public.sector VALUES (94, 'Machinery components', 12, 23);
INSERT INTO public.sector VALUES (91, 'Machinery equipment/tools', 12, 24);
INSERT INTO public.sector VALUES (224, 'Manufacture of machinery', 12, 25);
INSERT INTO public.sector VALUES (97, 'Maritime', 12, 26);
INSERT INTO public.sector VALUES (271, 'Aluminium and steel workboats', 97, 27);
INSERT INTO public.sector VALUES (269, 'Boat/Yacht building', 97, 28);
INSERT INTO public.sector VALUES (230, 'Ship repair and conversion', 97, 29);
INSERT INTO public.sector VALUES (93, 'Metal structures', 12, 30);
INSERT INTO public.sector VALUES (508, 'Other', 12, 31);
INSERT INTO public.sector VALUES (227, 'Repair and maintenance service', 12, 32);
INSERT INTO public.sector VALUES (11, 'Metalworking', 1, 33);
INSERT INTO public.sector VALUES (67, 'Construction of metal structures', 11, 34);
INSERT INTO public.sector VALUES (263, 'Houses and buildings', 11, 35);
INSERT INTO public.sector VALUES (267, 'Metal products', 11, 36);
INSERT INTO public.sector VALUES (542, 'Metal works', 11, 37);
INSERT INTO public.sector VALUES (75, 'CNC-machining', 542, 38);
INSERT INTO public.sector VALUES (62, 'Forgings, Fasteners', 542, 39);
INSERT INTO public.sector VALUES (69, 'Gas, Plasma, Laser cutting', 542, 40);
INSERT INTO public.sector VALUES (66, 'MIG, TIG, Aluminum welding', 542, 41);
INSERT INTO public.sector VALUES (9, 'Plastic and Rubber', 1, 42);
INSERT INTO public.sector VALUES (54, 'Packaging', 9, 43);
INSERT INTO public.sector VALUES (556, 'Plastic goods', 9, 44);
INSERT INTO public.sector VALUES (559, 'Plastic processing technology', 9, 45);
INSERT INTO public.sector VALUES (55, 'Blowing', 559, 46);
INSERT INTO public.sector VALUES (57, 'Moulding', 559, 47);
INSERT INTO public.sector VALUES (53, 'Plastics welding and processing', 559, 48);
INSERT INTO public.sector VALUES (560, 'Plastic profiles', 9, 49);
INSERT INTO public.sector VALUES (5, 'Printing', 1, 50);
INSERT INTO public.sector VALUES (148, 'Advertising', 5, 51);
INSERT INTO public.sector VALUES (150, 'Book/Periodicals printing', 5, 52);
INSERT INTO public.sector VALUES (145, 'Labelling and packaging printing', 5, 53);
INSERT INTO public.sector VALUES (7, 'Textile and Clothing', 1, 54);
INSERT INTO public.sector VALUES (44, 'Clothing', 7, 55);
INSERT INTO public.sector VALUES (45, 'Textile', 7, 56);
INSERT INTO public.sector VALUES (8, 'Wood', 1, 57);
INSERT INTO public.sector VALUES (337, 'Other (Wood)', 8, 58);
INSERT INTO public.sector VALUES (51, 'Wooden building materials', 8, 59);
INSERT INTO public.sector VALUES (47, 'Wooden houses', 8, 60);
INSERT INTO public.sector VALUES (3, 'Other', NULL, 61);
INSERT INTO public.sector VALUES (37, 'Creative industries', 3, 62);
INSERT INTO public.sector VALUES (29, 'Energy technology', 3, 63);
INSERT INTO public.sector VALUES (33, 'Environment', 3, 64);
INSERT INTO public.sector VALUES (2, 'Service', NULL, 65);
INSERT INTO public.sector VALUES (25, 'Business services', 2, 66);
INSERT INTO public.sector VALUES (35, 'Engineering', 2, 67);
INSERT INTO public.sector VALUES (28, 'Information Technology and Telecommunications', 2, 68);
INSERT INTO public.sector VALUES (581, 'Data processing, Web portals, E-marketing', 28, 69);
INSERT INTO public.sector VALUES (576, 'Programming, Consultancy', 28, 70);
INSERT INTO public.sector VALUES (121, 'Software, Hardware', 28, 71);
INSERT INTO public.sector VALUES (122, 'Telecommunications', 28, 72);
INSERT INTO public.sector VALUES (22, 'Tourism', 2, 73);
INSERT INTO public.sector VALUES (141, 'Translation services', 2, 74);
INSERT INTO public.sector VALUES (21, 'Transport and Logistics', 2, 75);
INSERT INTO public.sector VALUES (111, 'Air', 21, 76);
INSERT INTO public.sector VALUES (114, 'Rail', 21, 77);
INSERT INTO public.sector VALUES (112, 'Road', 21, 78);
INSERT INTO public.sector VALUES (113, 'Water', 21, 79);


--
-- Data for Name: submission; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.submission VALUES (1, 'Mari', true, '2026-09-16 17:42:21.090874+00', '2026-09-16 17:42:26.252702+00');
INSERT INTO public.submission VALUES (2, 'Roberto', true, '2026-09-16 17:42:42.494927+00', '2026-09-16 17:42:51.350607+00');
INSERT INTO public.submission VALUES (3, 'Kevin', true, '2026-09-16 17:43:07.4711+00', '2026-09-16 17:43:07.4711+00');
INSERT INTO public.submission VALUES (4, 'Miko S', true, '2026-09-16 17:43:24.561219+00', '2026-09-16 17:43:24.561219+00');
INSERT INTO public.submission VALUES (5, 'Kermo', true, '2026-09-16 17:43:51.843048+00', '2026-09-16 17:43:51.843048+00');


--
-- Data for Name: submission_sector; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.submission_sector VALUES (1, 18);
INSERT INTO public.submission_sector VALUES (1, 99);
INSERT INTO public.submission_sector VALUES (1, 394);
INSERT INTO public.submission_sector VALUES (1, 1);
INSERT INTO public.submission_sector VALUES (1, 94);
INSERT INTO public.submission_sector VALUES (2, 29);
INSERT INTO public.submission_sector VALUES (2, 1);
INSERT INTO public.submission_sector VALUES (2, 43);
INSERT INTO public.submission_sector VALUES (2, 33);
INSERT INTO public.submission_sector VALUES (2, 6);
INSERT INTO public.submission_sector VALUES (2, 37);
INSERT INTO public.submission_sector VALUES (3, 9);
INSERT INTO public.submission_sector VALUES (3, 111);
INSERT INTO public.submission_sector VALUES (3, 6);
INSERT INTO public.submission_sector VALUES (4, 57);
INSERT INTO public.submission_sector VALUES (4, 9);
INSERT INTO public.submission_sector VALUES (5, 230);
INSERT INTO public.submission_sector VALUES (5, 271);
INSERT INTO public.submission_sector VALUES (5, 269);


--
-- Name: submission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.submission_id_seq', 5, true);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: sector pk_sector; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sector
    ADD CONSTRAINT pk_sector PRIMARY KEY (id);


--
-- Name: submission pk_submission; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submission
    ADD CONSTRAINT pk_submission PRIMARY KEY (id);


--
-- Name: submission_sector pk_submission_sector; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submission_sector
    ADD CONSTRAINT pk_submission_sector PRIMARY KEY (submission_id, sector_id);


--
-- Name: sector uq_sector_parent_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sector
    ADD CONSTRAINT uq_sector_parent_name UNIQUE (parent_id, name);


--
-- Name: sector uq_sector_sort_order; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sector
    ADD CONSTRAINT uq_sector_sort_order UNIQUE (sort_order);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: idx_sector_parent_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sector_parent_id ON public.sector USING btree (parent_id);


--
-- Name: idx_submission_sector_sector_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_submission_sector_sector_id ON public.submission_sector USING btree (sector_id);


--
-- Name: sector fk_sector_parent; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sector
    ADD CONSTRAINT fk_sector_parent FOREIGN KEY (parent_id) REFERENCES public.sector(id);


--
-- Name: submission_sector fk_submission_sector_sector; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submission_sector
    ADD CONSTRAINT fk_submission_sector_sector FOREIGN KEY (sector_id) REFERENCES public.sector(id);


--
-- Name: submission_sector fk_submission_sector_submission; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submission_sector
    ADD CONSTRAINT fk_submission_sector_submission FOREIGN KEY (submission_id) REFERENCES public.submission(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict vbhCLHJG6ozDEzrMDvCabfbYNmbRyS5fVcAqZsT5fcv1NsMsK6GYO9cRsnI8ivJ

